backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: 'public/assets/images/uploads'
public_folder: '/assets/images/uploads'

collections:
  - name: 'posts' # Used in routes, e.g., /admin/collections/posts
    label: 'Posts' # Used in the UI
    label_singular: 'Post'
    folder: 'src/pages/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{fields.title}}_{{fields.subtitle}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: 'posts/{{filename}}'
    sortable_fields: ['order', 'start_datetime']
    view_filters:
      - label: 'Home Page'
        field: order
        pattern: \d+
      - label: 'Events'
        field: type
        pattern: 'Event'
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Home Page Order (blank to leave off home page)',
          name: 'order',
          widget: 'number',
        }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          options: ['Event'],
          default: ['Event'],
        }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'select',
          options: ['@layouts/PostLayout.astro'],
          default: ['@layouts/PostLayout.astro'],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Image URL', name: 'image_url', widget: 'string' }
      - {
          label: 'Start Date/Time',
          name: 'start_datetime',
          widget: 'datetime',
          format: 'MMMM DD, YYYY hh:mm',
        }
      - {
          label: 'End Date/Time (>= 23 hrs from start to make time blank)',
          name: 'end_datetime',
          widget: 'datetime',
          format: 'MMMM DD, YYYY hh:mm',
        }
      - {
          label: 'Location Display',
          name: 'location_display',
          widget: 'string',
        }
      - { label: 'Location URL', name: 'location_url', widget: 'string' }
      - {
          label: 'More Display',
          name: 'more_display',
          widget: 'string',
          default: 'Event Website',
        }
      - { label: 'External URL', name: 'external_url', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
